services:
  postgres:
    image: postgres:17
    container_name: uwb-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: uwb_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: uwb_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
